logging:
  level:
    root: INFO
    com.wallet.walletservice: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  web:
    error:
      include-message: never
      include-binding-errors: never
      include-stacktrace: never
      include-exception: false
  lifecycle:
    timeout-per-shutdown-phase: 30s # Allows the webhook strategy 30s to finish processing

server:
  shutdown: graceful

gateway:
  internal-secret: ${GATEWAY_INTERNAL_SECRET:default-edge-secret-string-123}