package com.wallet.walletservice.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

import java.math.BigDecimal;

@Data
@Builder
@Schema(description = "Response containing Razorpay order details")
public class PaymentOrderResponse {
    @Schema(description = "Order ID generated by Razorpay", example = "order_983hdks82")
    private String razorpayOrderId;

    @Schema(description = "Amount in INR major units, matching the stored local payment order amount.", example = "100.00")
    private BigDecimal amount;

    @Schema(description = "Currency code", example = "INR")
    private String currency;

    @Schema(description = "Current status of the order", example = "created")
    private String status;
}
