package com.wallet.walletservice.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;

@Data @Builder
@Schema(description = "Detailed response for a completed transaction")
public class TransactionResponse {
    @Schema(description = "Internal transaction ID", example = "50")
    private Long transactionId;

    @Schema(description = "Idempotency key associated with the transaction", example = "unique-id-123")
    private String idempotencyKey;

    @Schema(description = "Type of transaction", example = "TOPUP")
    private String type;

    @Schema(description = "Status of the transaction", example = "SUCCESS")
    private String status;

    @Schema(description = "Transaction description", example = "Wallet reload")
    private String description;

    @Schema(description = "Timestamp when the transaction was created")
    private OffsetDateTime createdAt;

    @Schema(description = "Individual ledger entries generated by this transaction")
    private List<LedgerEntryDto> ledgerEntries;

    @Data
    @Builder
    @Schema(description = "Summary of a ledger entry within a transaction")
    public static class LedgerEntryDto {
        @Schema(description = "Internal entry ID", example = "101")
        private Long entryId;

        @Schema(description = "ID of the affected wallet", example = "1")
        private Long walletId;

        @Schema(description = "Owner ID of the wallet", example = "user123")
        private String ownerId;

        @Schema(description = "Type of entry (CREDIT/DEBIT)", example = "CREDIT")
        private String entryType;

        @Schema(description = "Amount involved", example = "50.0")
        private BigDecimal amount;

        @Schema(description = "Wallet balance after this entry", example = "200.0")
        private BigDecimal balanceAfter;
    }
}
